- name: Setup nginx
  hosts: mousehost
  become: true

  vars:

  vars_files:
    
  handlers:

  tasks:

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx=1.29.6
        state: present

    - name: Render WireGuard config
      ansible.builtin.template:
        src: "../templates/wg0.conf.j2"
        dest: "{{ wg_config_path }}"
        mode: "0600"
      notify: Restart wireguard

    - name: Enable and start WireGuard
      ansible.builtin.systemd:
        name: "wg-quick@{{ wg_interface }}"
        enabled: true
        state: restarted
