- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - curl
      - gnupg2
      - ca-certificates
      - lsb-release
      - ubuntu-keyring
    state: present
    update_cache: true

- name: Download nginx signing key
  ansible.builtin.get_url:
    url: https://nginx.org/keys/nginx_signing.key
    dest: /usr/share/keyrings/nginx_signing.key
    mode: '0644'
    register: nginx_key
    retries: 3
    delay: 10
    until: nginx_key is succeeded

- name: Add nginx repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/usr/share/keyrings/nginx_signing.key]
      https://nginx.org/packages/mainline/ubuntu
      {{ ansible_distribution_release }} nginx
    filename: nginx
    state: present
    update_cache: true

- name: Install nginx
  ansible.builtin.apt:
    name: nginx=1.29.6-1~noble
    state: present

- name: Copy website
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Copy nginx conf
  ansible.builtin.copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: nginx
    group: nginx
    mode: '0644'

- name: Start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
