- name: Install cron
  ansible.builtin.apt:
    name: cron
    state: present

- name: Make a nginx backup directory
  ansible.builtin.file:
    path: /var/backups/nginx
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy nginx backup script
  ansible.builtin.template:
    src: files/backup_script.sh.j2
    dest: /usr/local/sbin/backup_script.sh
    owner: root
    group: root
    mode: '0755'

- name: Install nginx backup cron job
  ansible.builtin.template:
    src: files/cron_template.cron.j2
    dest: /etc/cron.d/nginx-backup
    owner: root
    group: root
    mode: '0644'
