name: Ansible lint

on:
  push:
    paths:
      - 'ansible/playbooks/**'
      - 'ansible/roles/**'
  pull_request:
    paths:
      - 'ansible/playbooks/**'
      - 'ansible/roles/**'

jobs:
  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
    with:
      args: '-p ansible/'
      working_directory: .
      requirements_file: requirements.yml
