name: Ansible lint

on:
  push:
    paths:
      - 'ansible/**'
      - 'requirements.yml'
  pull_request:
    paths:
      - 'ansible/**'
      - 'requirements.yml'

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug files
        run: |
          pwd
          ls -la
          find . -maxdepth 2 -name 'requirements.yml' -print

      - name: Install Ansible
        run: |
          python -m pip install ansible ansible-lint

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install -r requirements.yml

      - name: Run ansible-lint
        run: |
          ansible-lint ansible/
